api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "ct-bxgy-step-discount"
type = "function"
uid = "5be43bc1-e4e4-6b2c-4795-7b8d9583d406f80f80a7"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
