api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "bxgy-step-discount"
type = "function"
uid = "bac083e2-0ad0-8f12-74ca-e8572db557932a98cdd3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
